dist: trusty
language: tex
sudo: false

branches:
  except:
    /^v[0-9]+\.[0-9]+\.[0-9]+/

install:
  - cp -n ci/texlive* /tmp/
  - source /tmp/texlive_install.sh
  - /tmp/texlive_plugin_install.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

before_script:
  - source .env

script:
  - /tmp/texlive_generate.sh ${VERSION}.${TRAVIS_BUILD_NUMBER}

deploy:
  - provider: releases
    api_key: $GIT_AUTH
    skip_cleanup: true
    prerelease: true
    file: "${FILE_NAME}.pdf"
    tag_name: "v${VERSION}.${TRAVIS_BUILD_NUMBER}"
    name: "v${VERSION}.${TRAVIS_BUILD_NUMBER}"
    on:
      tags: false
      branch: "master"
  - provider: releases
    api_key: $GIT_AUTH
    skip_cleanup: true
    file:
      - "${FILE_NAME}.pdf"
    on:
      tags: true
