name: Generate Documentation
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

jobs:
  generate-documenation:
    name: Generate PDF
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Texlive
      uses: xu-cheng/texlive-action/full@v1
      with:
        run: |
          cp -n texlive* /tmp/
          tlmgr install koma-script etoolbox logreq biblatex-apa csquotes siunitx oberdiek tocloft abstract pdfpages enumitem
          tlmgr install psnfss ms caption ec l3kernel l3packages zapfding symbol helvetic textpos glossaries xkeyval mfirstuc
          tlmgr install textcase xfor datatool substr fp tracklang pdfx iftex xcolor xmpincl glossaries-german
          tlmgr install bitset letltxmacro pdfescape pdflscape ragged2e lipsum
          source .env
          pdflatex -interaction=nonstopmode -halt-on-error BA-Dokumentation-Template.tex
          biber *.bcf
          makeglossaries BA-Dokumentation-Template
          pdflatex -interaction=nonstopmode -halt-on-error BA-Dokumentation-Template.tex
          pdflatex -interaction=nonstopmode -halt-on-error "\providecommand{\docversion}{$VERSION.$GITHUB_RUN_ID} \input{BA-Dokumentation-Template.tex}"
          pdflatex -interaction=nonstopmode -halt-on-error ./web-abstract/WebAbstract.tex
          pdflatex -interaction=nonstopmode -halt-on-error ./web-abstract/WebAbstract.tex
          mv BA-Dokumentation-Template.pdf $FILE_NAME.pdf

    - name: Save Documentation
      uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: '*.pdf'
